[package]
name = "fmp"
version = "1.1.6"
edition = "2021"
authors = ["Luke Wilkinson <wilkinsonluke@proton.me>"]
license = "GPL-3.0"
description = "Simple password manager"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
cmd_lib = "1.9.0"
rustc-serialize = "0.3.25"
rand = "0.8.5"
simple-home-dir = "0.4.6"
import-handle = "1.0.4"
ilog = "1.0.1"
dir_input = "1.0.1"