[package]
name = "fmp"
version = "1.2.21"
edition = "2021"
authors = ["Luke Wilkinson <wilkinsonluke@proton.me>"]
license = "GPL-3.0"
description = "Simple password manager"
repository = "https://github.com/TT1882/Forgot-My-Password.git"
keywords = ["cli", "crypto", "cryptography", "serde", "rust"]

[dependencies]
dirs = "6.0.0"
serde_json = "1.0.137"
serde = { version = "1.0.137", features = ["derive"] }
input-handle = "1.0.4"
clap = { version = "4.5.26", features = ["derive"] }
rand = "0.9.0"
prettytable-rs = "0.10.0"